version: '3.2'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: testedb
    ports:
      - '3306:3306'
    volumes:
      - '/data/mysql:/var/lib/mysql'
    networks:
      - minha-rede
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'
    networks:
      - minha-rede
networks:
  minha-rede:
    driver: bridge
